# Generated by Django 2.2.6 on 2019-10-18 19:37

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191014_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=False, upload_to=blog.models.upload_location),
            preserve_default=False,
        ),
    ]
