# Generated by Django 3.0.2 on 2020-03-31 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191020_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='blog.BlogPost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='blog.BlogPost'),
        ),
    ]
