# Generated by Django 3.0.2 on 2020-04-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200331_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(choices=[('moltivate', 'Motivational'), ('inspire', 'Inspiration'), ('education', 'Educational')], default=True, max_length=100),
            preserve_default=False,
        ),
    ]
