# Generated by Django 3.0.2 on 2020-04-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(choices=[('Motivational', 'Motivational'), ('Inspiration', 'Inspiration'), ('Educational', 'Educational')], max_length=100),
        ),
    ]
