# Generated by Django 3.0.2 on 2020-04-02 18:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200402_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=True, upload_to=blog.models.upload_location),
            preserve_default=False,
        ),
    ]
